package dk.magenta.databroker.models.core;
// Generated Nov 5, 2014 3:21:03 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PasswordLogin generated by hbm2java
 */
@Entity
@Table(name="PasswordLogin"
)
public class PasswordLogin  implements java.io.Serializable {


     private Integer passwordLoginId;
     private Consumer consumer;
     private String login;
     private String secret;

    public PasswordLogin() {
    }

    public PasswordLogin(Consumer consumer, String login, String secret) {
       this.consumer = consumer;
       this.login = login;
       this.secret = secret;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="PasswordLoginId", unique=true, nullable=false)
    public Integer getPasswordLoginId() {
        return this.passwordLoginId;
    }
    
    public void setPasswordLoginId(Integer passwordLoginId) {
        this.passwordLoginId = passwordLoginId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ConsumerId", nullable=false)
    public Consumer getConsumer() {
        return this.consumer;
    }
    
    public void setConsumer(Consumer consumer) {
        this.consumer = consumer;
    }
    
    @Column(name="Login", nullable=false)
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    
    @Column(name="Secret", nullable=false, length=34)
    public String getSecret() {
        return this.secret;
    }
    
    public void setSecret(String secret) {
        this.secret = secret;
    }




}


