package dk.magenta.databroker.models.core;
// Generated Nov 5, 2014 3:21:03 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UpdateLog generated by hbm2java
 */
@Entity
@Table(name="UpdateLog"
)
public class UpdateLog  implements java.io.Serializable {


     private Long updateLogId;
     private UpdateType updateType;
     private DataProvider dataProvider;
     private Integer count;
     private boolean isPush;
     private Integer remoteIp;

    public UpdateLog() {
    }

	
    public UpdateLog(UpdateType updateType, DataProvider dataProvider, boolean isPush) {
        this.updateType = updateType;
        this.dataProvider = dataProvider;
        this.isPush = isPush;
    }
    public UpdateLog(UpdateType updateType, DataProvider dataProvider, Integer count, boolean isPush, Integer remoteIp) {
       this.updateType = updateType;
       this.dataProvider = dataProvider;
       this.count = count;
       this.isPush = isPush;
       this.remoteIp = remoteIp;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="UpdateLogId", unique=true, nullable=false)
    public Long getUpdateLogId() {
        return this.updateLogId;
    }
    
    public void setUpdateLogId(Long updateLogId) {
        this.updateLogId = updateLogId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="UpdateTypeId", nullable=false)
    public UpdateType getUpdateType() {
        return this.updateType;
    }
    
    public void setUpdateType(UpdateType updateType) {
        this.updateType = updateType;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SourceDataProviderId", nullable=false)
    public DataProvider getDataProvider() {
        return this.dataProvider;
    }
    
    public void setDataProvider(DataProvider dataProvider) {
        this.dataProvider = dataProvider;
    }
    
    @Column(name="Count")
    public Integer getCount() {
        return this.count;
    }
    
    public void setCount(Integer count) {
        this.count = count;
    }
    
    @Column(name="IsPush", nullable=false)
    public boolean isIsPush() {
        return this.isPush;
    }
    
    public void setIsPush(boolean isPush) {
        this.isPush = isPush;
    }
    
    @Column(name="RemoteIp")
    public Integer getRemoteIp() {
        return this.remoteIp;
    }
    
    public void setRemoteIp(Integer remoteIp) {
        this.remoteIp = remoteIp;
    }




}


