package dk.magenta.databroker.core.model;
// Generated Nov 5, 2014 3:21:03 PM by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ConsumerStatus generated by hbm2java
 */
@Entity
@Table(name="ConsumerStatus"
)
public class ConsumerStatus  implements java.io.Serializable {


     private Integer consumerStatusId;
     private String name;
     private String description;
     private Set<Consumer> consumers = new HashSet<Consumer>(0);

    public ConsumerStatus() {
    }

	
    public ConsumerStatus(String name, String description) {
        this.name = name;
        this.description = description;
    }
    public ConsumerStatus(String name, String description, Set<Consumer> consumers) {
       this.name = name;
       this.description = description;
       this.consumers = consumers;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="ConsumerStatusId", unique=true, nullable=false)
    public Integer getConsumerStatusId() {
        return this.consumerStatusId;
    }
    
    public void setConsumerStatusId(Integer consumerStatusId) {
        this.consumerStatusId = consumerStatusId;
    }
    
    @Column(name="Name", nullable=false)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="Description", nullable=false, length=65535)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="consumerStatus")
    public Set<Consumer> getConsumers() {
        return this.consumers;
    }
    
    public void setConsumers(Set<Consumer> consumers) {
        this.consumers = consumers;
    }




}


