package dk.magenta.databroker.core.model;
// Generated Nov 5, 2014 3:21:03 PM by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DataProvider generated by hbm2java
 */
@Entity
@Table(name="DataProvider"
)
public class DataProvider  implements java.io.Serializable {


     private Integer dataProviderId;
     private String uuid;
     private String type;
     private boolean active;
     private int priority;
     private String cronSchedule;
     private Set<UpdateLog> updateLogs = new HashSet<UpdateLog>(0);

    public DataProvider() {
    }

	
    public DataProvider(String uuid, String type, boolean active, int priority) {
        this.uuid = uuid;
        this.type = type;
        this.active = active;
        this.priority = priority;
    }
    public DataProvider(String uuid, String type, boolean active, int priority, String cronSchedule, Set<UpdateLog> updateLogs) {
       this.uuid = uuid;
       this.type = type;
       this.active = active;
       this.priority = priority;
       this.cronSchedule = cronSchedule;
       this.updateLogs = updateLogs;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="DataProviderId", unique=true, nullable=false)
    public Integer getDataProviderId() {
        return this.dataProviderId;
    }
    
    public void setDataProviderId(Integer dataProviderId) {
        this.dataProviderId = dataProviderId;
    }
    
    @Column(name="UUID", nullable=false, length=36)
    public String getUuid() {
        return this.uuid;
    }
    
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }
    
    @Column(name="type", nullable=false)
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    
    @Column(name="active", nullable=false)
    public boolean isActive() {
        return this.active;
    }
    
    public void setActive(boolean active) {
        this.active = active;
    }
    
    @Column(name="priority", nullable=false)
    public int getPriority() {
        return this.priority;
    }
    
    public void setPriority(int priority) {
        this.priority = priority;
    }
    
    @Column(name="cronSchedule")
    public String getCronSchedule() {
        return this.cronSchedule;
    }
    
    public void setCronSchedule(String cronSchedule) {
        this.cronSchedule = cronSchedule;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="dataProvider")
    public Set<UpdateLog> getUpdateLogs() {
        return this.updateLogs;
    }
    
    public void setUpdateLogs(Set<UpdateLog> updateLogs) {
        this.updateLogs = updateLogs;
    }




}


