package dk.magenta.databroker.core.model;
// Generated Nov 5, 2014 3:21:03 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * RequestLogError generated by hbm2java
 */
@Entity
@Table(name="RequestLogError"
)
public class RequestLogError  implements java.io.Serializable {


     private Integer requestLogErrorId;
     private RequestLog requestLog;
     private String errorMessage;

    public RequestLogError() {
    }

    public RequestLogError(RequestLog requestLog, String errorMessage) {
       this.requestLog = requestLog;
       this.errorMessage = errorMessage;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="RequestLogErrorId", unique=true, nullable=false)
    public Integer getRequestLogErrorId() {
        return this.requestLogErrorId;
    }
    
    public void setRequestLogErrorId(Integer requestLogErrorId) {
        this.requestLogErrorId = requestLogErrorId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="RequestLogId", nullable=false)
    public RequestLog getRequestLog() {
        return this.requestLog;
    }
    
    public void setRequestLog(RequestLog requestLog) {
        this.requestLog = requestLog;
    }
    
    @Column(name="ErrorMessage", nullable=false, length=65535)
    public String getErrorMessage() {
        return this.errorMessage;
    }
    
    public void setErrorMessage(String errorMessage) {
        this.errorMessage = errorMessage;
    }




}


